update python script to support Python3
clsid2/mpc-hc pull request #878
Opened 2021-02-04 06:36 UTC by lifegpc

I test it with Python 3.7.4. Works well.

2021-02-11 12:51 UTC, clsid2 commented
I assume this is not backwards compatible with v2?
In that case the compilation instructions document also needs to be updated.

2021-02-11 12:52 UTC, lifegpc commented
yea.

2021-02-11 13:22 UTC, lifegpc commented
done.

2021-02-13 07:48 UTC, waynon requested changes
It's better to use the currently latest version (3.9.1) of Python in the document.

2021-02-13 07:48 UTC, waynon commented on build.user_example.bat
> +SET "MPCHC_PYTHON=C:\Program Files\Python37"
It's better to use Python 3.9.1 (currently latest version) or vaguely use Python 3.x or later

2021-02-13 07:48 UTC, waynon commented on docs/Compilation.md
> +1. Install Python version 3.7.9 from <https://www.python.org/downloads/release/python-379/> (You can use Python 3.6 or later version)
It's better to use the latest version 3.9.1 in the document.

2021-02-17 01:03 UTC, lifegpc commented
Maybe I can change it to 3.8. 3.9 can not used on win7.

2021-02-17 01:32 UTC, clsid2 commented
3.8.7 works in Win7

2021-02-17 01:39 UTC, merged